# Squash Bot Commits
name: Daily Squash

on:
  # Runs every 24 hours
  schedule:
    - cron: '0 */24 * * *'

  # Manual updates
  workflow_dispatch:

jobs:
  squash:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history

      - name: Squash Last 3 Bot Commits
        env:
          # EDITOR: vim
          BOT_EMAIL: "action@github.com"
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Rebase instruction to squash bot commits only
          git log --pretty=format:'%H %ae' HEAD~10 |
          awk -v bot_email=$BOT_EMAIL 'BEGIN { first=1 } {
            if (first) {
              print "pick "$1;
              first=0;
            } else if ($2 == bot_email) {
              print "squash "$1;
            } else {
              print "pick "$1;
            }
          }' > /tmp/rebase-instructions

          # Automate Rebase
          EDITOR="cat /tmp/rebase-instructions >" git rebase -i HEAD~10
  
      - name: Force push to the branch
        run: |
          git commit --amend -m "squash"
          git push origin main --force
          
