# Squash Bot Commits
name: Daily Squash

on:
  # Runs every 24 hours
  schedule:
    - cron: '0 */24 * * *'

  # Manual updates
  workflow_dispatch:

jobs:
  squash:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history

      - name: Squash Bot Commits
        env:
          # EDITOR: vim
          BOT_EMAIL: "action@github.com"
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          # Get authors of the last 10 commits
          authors=$(git log -10 --pretty=format:"%aN")
          
          # Prepare the rebase instructions
          instructions=""

          # Loop through the authors to decide which commits to pick or squash
          count=0
          echo "$authors" | while read author; do
            if [[ "$author" == "GitHub Action" ]] && [[ "$count" -ne 0 ]]; then
              instructions+="squash "
            else
              instructions+="pick "
            fi
            
            # Increment count if it's a bot commit
            [[ "$author" == "GitHub Action" ]] && count=$((count+1))
            
            instructions+=$(git rev-parse HEAD~$count)
            instructions+=$'\n'
          done

          # Save the instructions to a temporary file
          echo "$instructions" > /tmp/rebase-instructions

          # Perform the rebase
          EDITOR="cat /tmp/rebase-instructions >" git rebase -i HEAD~10

      - name: Force push to the branch
        run: |
          git commit --amend -m "squash"
          git push origin main --force
          
