# Squash Bot Commits
name: Weekly Squash

on:
  # Runs every week
  schedule:
    - cron: '0 0 * * 0'

  # Manual updates
  workflow_dispatch:

jobs:
  squash:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history

      - name: Squash Bot Commits
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          # Get authors of the last 21 commits
          authors=$(git log -21 --pretty=format:"%aN")
          
          # Temporary file for rebase instructions
          tmp_file="/tmp/rebase-instructions"
          >$tmp_file
          
          # Loop through the authors to pick or squash
          count=0
          echo "$authors" | while read author; do
            if [[ "$author" == "GitHub Action" ]] && [[ "$count" -ne 0 ]]; then
              echo "squash $(git rev-parse HEAD~$count)" >> $tmp_file
            else
              echo "pick $(git rev-parse HEAD~$count)" >> $tmp_file
            fi
            
            # Increment count if it's a bot commit
            [[ "$author" == "GitHub Action" ]] && count=$((count+1))
          done

          # Perform the rebase
          EDITOR="cat" git rebase -i HEAD~21 < /tmp/rebase-instructions

      - name: Force push to the branch
        run: |
          git commit --amend -m "squash"
          git push origin main --force
